name: Automatizar Registro de Hitos

on:
  schedule:
    # Se ejecuta cada 15 minutos
    - cron: '*/15 * * * *'
  workflow_dispatch:
    # Permite la ejecución manual desde la pestaña Actions de GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout del repositorio
        uses: actions/checkout@v3

      - name: 2. Configurar Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: 3. Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
      - name: 4. Crear archivo de credenciales de Google
        # Este paso crucial toma el secreto de GitHub y lo escribe en el archivo
        # que el script espera encontrar.
        run: |
          echo "Creando el archivo google_credentials.json..."
          mkdir -p credentials
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials/google_credentials.json
          echo "Archivo de credenciales creado."

      - name: 5. Ejecutar el script de automatización
        run: python main.py
